### ISSUE TITLE
Allow to configure axios with keepAlive:true

### ISSUE THREAD

**Issue by nottmey** [scayle/storefront-api-ts-sdk#6]
Hello there,

for several clients of yours we use the BapiClient inside Firebase Functions.

When optimizing the functions we noticed that we cannot follow the best practices of Firebase:
https://firebase.google.com/docs/functions/networking#maintaining_persistent_connections

This is because the current implementation of the BapiClient doesn't allow to set the underlying httpAgent/httpsAgent.
It would be neat to do this without forking your library. Here is an example how axios is intending to allow this:
https://github.com/axios/axios/issues/1846#issuecomment-434208900

Best regards
Malte

**Comment by HenriBeck** [comment]
@nottmey, I think this should already be possible since we are using the default axios instance, so something along these lines should already work:

```ts
axios.defaults.httpsAgent = new https.Agent({ keepAlive: true });
```

We will leave this ticket still open to be able to customize the axios instance to be used

**Comment by HenriBeck** [comment]
We have moved to a `fetch` implementation now
